logging:
    version: 1

    root:
        level: DEBUG
        handlers: [consoleHandler]

    formatters:
        simpleFormatter:
            format: '%(asctime)s || %(levelname)-8s|| %(message)s'

    handlers:
        consoleHandler:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simpleFormatter
            stream: ext://sys.stdout

        doorLockFileHandler: 
            class: logging.FileHandler
            level: DEBUG
            formatter: simpleFormatter
            filename: /home/pi/code/makeictelectronicdoor/logs/door-lock.log

        enrollFileHandler: 
            class: logging.FileHandler
            level: DEBUG
            formatter: simpleFormatter
            filename: /home/pi/code/makeictelectronicdoor/logs/enroll.log

    loggers: 
        door-lock:
            qualname: door-lock 
            level: DEBUG
            handlers: [doorLockFileHandler, consoleHandler]
            propagate: False

        enroll:
            qualname: enroll
            level: DEBUG
            handlers: [consoleHandler, enrollFileHandler]
            propagate: False
